"""Visualization functions for MNE-Denoise."""

from .components import (
    plot_component_epochs_image,
    plot_component_patterns,
    plot_component_score_curve,
    plot_component_spectrogram,
    plot_component_summary,
    plot_component_time_series,
)
from .signals import (
    plot_channel_time_course_comparison,
    plot_evoked_gfp_comparison,
    plot_grand_average_evokeds,
    plot_power_ratio_map,
    plot_signal_overlay,
)
from .spectra import (
    plot_component_psd_comparison,
    plot_narrowband_score_scan,
    plot_psd_comparison,
    plot_psd_gallery,
    plot_psd_overlay,
    plot_psd_zoom_comparison,
    plot_spectrogram_comparison,
    plot_time_frequency_mask,
)
from .stats import (
    plot_forest,
    plot_harmonic_attenuation,
    plot_metric_bars,
    plot_metric_comparison,
    plot_metric_slopes,
    plot_metric_violins,
    plot_null_distribution,
    plot_tradeoff_scatter,
)
from .summary import (
    plot_component_cleaning_summary,
    plot_condition_interaction_summary,
    plot_denoising_summary,
    plot_endpoint_metrics_summary,
    plot_group_condition_interaction_summary,
    plot_metric_tradeoff_summary,
    plot_signal_diagnostics_summary,
)
from .theme import (
    COLORS,
    DEFAULT_DPI,
    DEFAULT_FIGSIZE,
    DIVERGING_CMAP,
    FONTS,
    METHOD_COLORS,
    SEQUENTIAL_CMAP,
    SERIES_COLORS,
    get_color,
    get_series_color,
    get_theme_rc,
    set_theme,
    style_axes,
    themed_figure,
    themed_legend,
    use_theme,
)

__all__ = [
    # Theme
    "COLORS",
    "FONTS",
    "METHOD_COLORS",
    "SERIES_COLORS",
    "SEQUENTIAL_CMAP",
    "DIVERGING_CMAP",
    "DEFAULT_FIGSIZE",
    "DEFAULT_DPI",
    "set_theme",
    "use_theme",
    "get_theme_rc",
    "get_color",
    "get_series_color",
    "style_axes",
    "themed_figure",
    "themed_legend",
    # Component plots
    "plot_component_summary",
    "plot_component_patterns",
    "plot_component_score_curve",
    "plot_component_epochs_image",
    "plot_component_time_series",
    "plot_component_spectrogram",
    # Spectral helpers
    "plot_narrowband_score_scan",
    "plot_time_frequency_mask",
    # Comparison plots
    "plot_psd_gallery",
    "plot_psd_comparison",
    "plot_psd_overlay",
    "plot_psd_zoom_comparison",
    "plot_channel_time_course_comparison",
    "plot_evoked_gfp_comparison",
    "plot_spectrogram_comparison",
    "plot_power_ratio_map",
    "plot_grand_average_evokeds",
    "plot_denoising_summary",
    "plot_component_psd_comparison",
    "plot_signal_overlay",
    # Summary composers
    "plot_component_cleaning_summary",
    "plot_signal_diagnostics_summary",
    "plot_condition_interaction_summary",
    "plot_group_condition_interaction_summary",
    "plot_endpoint_metrics_summary",
    # Stats plots
    "plot_metric_bars",
    "plot_tradeoff_scatter",
    "plot_metric_comparison",
    "plot_harmonic_attenuation",
    "plot_metric_slopes",
    "plot_metric_violins",
    "plot_null_distribution",
    "plot_forest",
    "plot_metric_tradeoff_summary",
]
