name: Changelog

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  changelog:
    name: Check changelog entry
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: scientific-python/action-towncrier-changelog@f9c7df9a9f8b55cb0c12d94d14b281e9bcd101c0  # v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_USERNAME: changelog-bot
